get:
  listup:
    owner: "sky0621"
    accessToken: ""
    maxPage: 10

  filter:
    name: "^study-.*"
    language: "Go"

  checkout:
    targetOwner: "sky0621"
    branch: "master"
    outputPath: "/tmp/gowork/src/github.com/sky0621/"
