get:
  listup:
    owner: "sky0621"
    accessToken: ""
    maxPage: 10

  filter:
    name: "^study-.*"
    language: "Go"

  checkout:
    access:
      user: ""
      password: ""
    target:
      owner: "sky0621"
    output:
      path: "/tmp/gowork/src/github.com/sky0621/"
