get:
  listup:
    owner: "sky0621"
    accessToken: ""
    maxPage: 10

  filter:
    name: "^study-.*"
    language: "Go"

  checkout:
    target:
      owner: "sky0621"
      branch: "master"
    output:
      path: "/tmp/gowork/src/github.com/sky0621/"
gen:
  testcode:
    input:
      path: "/tmp/gowork/src/github.com/sky0621/"
      filter:
        name: "^study-.*"
    output:
      path: "/tmp/gowork/testcode/github.com/sky0621/"

